
title: Mr Mike Mahoney's Resume
url: 'MrMikeMahoney.github.io'
baseurl:  #change it according to your repository name



# Profile information
yourname: Mike Mahoney  ## put your name
title: 'Data Scientist'  ## your title
location: Texas, open to relocation


## Social Profiles
facebook: https://www.facebook.com/profile.php?id=29617842m  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
github: https://github.com/MrMikeMahoney
linkedin: https://www.linkedin.com/in/michael-mahoney-236b08109/  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
